### ISSUE TITLE
Fix time zones

### ISSUE THREAD

**Issue by sambhavsaxena** [sambhavsaxena/flexmail#1]
The time zones fetched by the API is of the location where the server is located.
Fix it to the local timezone of the browser.

**Comment by vaibhav-305** [comment]
hi, I would like to work on this, can u please assign this to me ?

**Comment by sambhavsaxena** [comment]
@vaibhav-305 all yours

**Comment by sambhavsaxena** [comment]
@vaibhav-305 thanks for your time.
You can checkout other JavaScript repositories for more such contributions.
