### ISSUE TITLE
Any way to bypass temp mail detector?

### ISSUE THREAD

**Issue by Box-boi** [sambhavsaxena/flexmail#4]
The website below detects temp mails. 
It probably has to do something with DKIM/DMARC/SPF records.
Some websites refuse to send mails if it's detected as a temp mail.

https://quickemailverification.com/tools/disposable-email-address-detector

They're apparently open-source too, the link is https://github.com/quickemailverification

**Comment by sambhavsaxena** [comment]
Hey sorry for late response, I totally forgot about this. 
I don't particularly understand the verification process going on in the repository, so in order to understand it better, I've now cloned the repo and I would go through the code and look if there's anything useful I could find.
